version: "3.9"
services:
  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:5173"
    depends_on:
      - backend
  backend:
    build:
      context: ./nest-backend
      dockerfile: Dockerfile
    ports:
      - "8081:3333"
    depends_on:
      - database
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ia_dev
    ports:
      - "8082:5432"