#Version actual docker-compose.yml

version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    env_file:
      - ./nest-backend/.env
    ports:
      - "5432:5432"
    networks:
      - ia_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    #build:
    #  context: ./nest-backend
    #  dockerfile: Dockerfile
    image: docker.io/eddindocker/nest-backend
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - ia_network
    env_file:
      - ./nest-backend/.env
  frontend:
    #build:
    #  context: ./react-frontend
    #  dockerfile: Dockerfile
    image: docker.io/eddindocker/react-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - postgres
    networks:
      - ia_network
  
networks:
  ia_network:

volumes:
  postgres_data: