#Version actual docker-compose.yml

version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    env_file:
      - ./nest-backend/.env
    #environment:
      #POSTGRES_DB: ${POSTGRES_DB}
      #POSTGRES_USER: ${POSTGRES_USER}
      #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - ia_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./nest-backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - ia_network
    env_file:
      - ./nest-backend/.env
    command: sh -c "npm run wait && npm run start:prod"
    #environment:
      #DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - postgres
    networks:
      - ia_network
  
networks:
  ia_network:
    #driver: bridge

volumes:
  postgres_data: