version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ia_dev
    networks:
      - plataforma-ia
  #test-db:
  #  image: postgres:13
  #  ports:
  #    - 5435:5432
  #  environment:
  #    POSTGRES_USER: postgres
  #    POSTGRES_PASSWORD: postgres
  #    POSTGRES_DB: ia_test
  #  networks:
  #    - plataformaIA
  #prod-db:
  #  image: postgres:13
  #  ports:
  #    - 5440:5432
  #  environment:
  #    POSTGRES_USER: postgres
  #    POSTGRES_PASSWORD: postgres
  #    POSTGRES_DB: ia_prod
  #  networks:
  #    - plataformaIA
networks:
  plataforma-ia: